### ISSUE TITLE
Run always fails with "--kf-max-dist=0 --kf-min-dist=0"

### ISSUE THREAD

**Issue by urvangjoshi** [tdaede/awcy#114]
Here's a sample run on baseline, which failed.
https://arewecompressedyet.com/?job=ALL_baseline%402017-01-17T23%3A21%3A32.371Z

I've also tried several other runs (with different compile options) with the same issue every time.

It wasn't clear to me from the logs what the problem is.

**Comment by tdaede** [comment]
Those videos segfault locally for me (on aspen for example):

$AOMENC --codec=$CODEC --ivf --frame-parallel=0 --tile-columns=0 --auto-alt-ref=2 --cpu-used=0 --passes=2 --threads=1 --kf-min-dist=$KFINT --kf-max-dist=$KFINT --lag-in-frames=25 --end-usage=q --cq-level=$x -o $BASENAME.ivf $EXTRA_OPTIONS $FILE
Pass 1/2 frame   22/21      3696B 1722519 us 12.77 fps [ETA  0:00:02] Segmentation fault (core dumped)

Backtrace:
```
#0  0x00000000004c6919 in aom_sad16x16x4d_sse2 ()
#1  0x000000000059a1e1 in av1_diamond_search_sad_c ()
#2  0x000000000057ad46 in first_pass_motion_search ()
#3  0x000000000057cab0 in av1_first_pass ()
#4  0x000000000049b32f in av1_get_compressed_data ()
#5  0x000000000047fbfd in encoder_encode ()
#6  0x000000000047d517 in aom_codec_encode ()
#7  0x00000000004038e9 in main ()
```

Test set is here if you don't have it: https://media.xiph.org/video/derf/objective-1-fast.tar.gz

Looks like the "Segmentation fault" line gets dropped, probably because it's emitted by the shell and not by the executable itself. I'll see if I can print something nice for that return code.

**Comment by urvangjoshi** [comment]
Created this aomedia issue to track: http://crbug.com/aomedia/133
Meanwhile, keeping this one open if you want to print a useful message for such segfaults.
