### ISSUE TITLE
Exception while handling exception

### ISSUE THREAD

**Issue by tdaede** [tdaede/awcy#149]
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: 2017-04-10 23:53:14.386 Retrying work  Netflix_FoodMarket_1920x1080_60f
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: 2017-04-10 23:53:14.386 Encoding Netflix_TunnelFlag_1920x1080_60fps_8bi
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: 2017-04-10 23:53:14.388 Logging results...
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: ERROR:tornado.application:Exception in callback functools.partial(<func
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: Traceback (most recent call last):
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: File "./rd_server.py", line 287, in scheduler_tick
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: run.reduce()
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: File "/home/awcy/awcy/rd_tool/work.py", line 61, in reduce
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: f = open((self.prefix+'/'+work.filename+'-daala.out').encode('utf-8'),'
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: OSError: [Errno 24] Too many open files: b'../runs//base_low@2017-04-11
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: During handling of the above exception, another exception occurred:
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: Traceback (most recent call last):
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/tornad
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: ret = callback()
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: File "/opt/rh/rh-python34/root/usr/lib64/python3.4/site-packages/tornad
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: return fn(*args, **kwargs)
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: File "./rd_server.py", line 288, in scheduler_tick
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: except e:
Apr 10 23:53:14 arewecompressedyet.com scl[19615]: NameError: name 'e' is not defined

**Comment by tdaede** [comment]
fixed by bf3a4d2848eca091dbe461208d829513e24f48b5
